###################### Heartbeat Configuration #######################

http.enabled: true
http.port: 5066
http.host: "${ES_NET}.7"  

monitoring:
  enabled: false
  cluster_uuid: "${CLUSTER_UUID}"

processors:
  - add_docker_metadata: ~
  # - add_cloud_metadata: ~
  # - add_kubernetes_metadata: ~
  # https://www.elastic.co/guide/en/beats/heartbeat/current/add-observer-metadata.html
  - add_tags:
      tags: ["${STAGE}"]
      target: "environment"
  - add_tags:
      tags: ["${APP_HOST}-${APP_ID}"]
      target: "app.id"

instrumentation:
  enabled: true
  environment: "${STAGE}"
  hosts: ["${ELASTIC_APM_SERVER_URL}"]
  api_key: "${ELASTIC_APM_API_KEY}"
  tags: ["${APP_HOST}-${APP_ID}"]

heartbeat.config.monitors:
  # Directory + glob pattern to search for configuration files
  path: ${path.config}/monitors.d/*.yml
  # If enabled, heartbeat will periodically check the config.monitors path for changes
  reload.enabled: false
  # How often to check for changes
  reload.period: 5s

heartbeat.monitors:

# - type: http
#   schedule: '* * * * * *'
#   id: http-service
#   name: HTTP Service
#   data_stream.namespace: default
#   service.name: heartbeat-http
#   check.response.status: [401]
#   tags: [web]
#   hosts:
#     - https://traefik.eliasondrej.com

- type: tcp
  schedule: '* * * * * *'
  id: tcp-service
  name: TCP Service
  data_stream.namespace: default
  service.name: heartbeat-tcp
  tags: [tcp]
  hosts:
    - es01.${APP_NET}:${ES_PORT}
    - logstash.${APP_NET}:${LOGSTASH_MONITOR_PORT}
    - kibana.${APP_NET}:${KIBANA_PORT}
    - work.kibana.${APP_NET}:80
    - filebeat.${APP_NET}:${MONITOR_PORT}
    - apm-server.${APP_NET}:${MONITOR_PORT}
    - heartbeat.${APP_NET}:${MONITOR_PORT}
    - metricbeat.${APP_NET}:${MONITOR_PORT}

#  - type: icmp
#   schedule: '*/15 * * * * *'
#   id: icmp-service
#   name: ICMP Service
#   data_stream.namespace: default
#   service.name: heartbeat-icmp
#   tags: [icmp]
#   hosts:
#     - heartbeat.${APP_NET}

heartbeat.scheduler:
  limit: 2
heartbeat.jobs:
  http:
    limit: 3
  browser:
    limit: 2    

output:
  elasticsearch:
    hosts: ["https://es01.${APP_NET}:${ES_PORT}"]
    protocol: "https"
    username: "${ELASTICSEARCH_USERNAME}"
    password: "${ELASTICSEARCH_PASSWORD}"
    ssl:
      enabled: true
      certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
      verification_mode: "${VERIFICATION_MODE}"

