# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-beat.html

- module: beat
  xpack.enabled: true
  period: 10s
  hosts: 
    # - apm-server.${APP_NET}:${MONITOR_PORT}
    - heartbeat.${APP_NET}:${MONITOR_PORT}
    - metricbeat.${APP_NET}:${MONITOR_PORT}
    - filebeat.${APP_NET}:${MONITOR_PORT}
  #username: "beats_system"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  # ssl:
  #  enabled: true
  #  certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
  #  verification_mode: "${VERIFICATION_MODE}"
