# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/main/metricbeat-module-elasticsearch.html

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: 
    - "http://es01.${APP_NET}:9200"
    - "http://es02.${APP_NET}:9201"
  protocol: "http"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  ssl:
    enabled: false
    # enabled: true
    # certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
    # verification_mode: "${VERIFICATION_MODE}"

