###################### Metricbeat Configuration #######################

http.enabled: true
http.port: 5066
http.host: "${ES_NET}.8"

monitoring:
  enabled: false
  cluster_uuid: "${CLUSTER_UUID}"

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  # - add_host_metadata:
  #     when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  # - add_cloud_metadata: ~
  # - add_kubernetes_metadata: ~
  - add_tags:
      tags: ["${STAGE}"]
      target: "environment"
  - add_tags:
      tags: ["${APP_HOST}-${APP_ID}"]
      target: "app.id"

instrumentation:
  enabled: true
  environment: "${STAGE}"
  hosts: ["${ELASTIC_APM_SERVER_URL}"]
  # api_key: "${ELASTIC_APM_API_KEY}"
  tags: ["${APP_HOST}-${APP_ID}"]

# hostPid: true

inputs:
  - type: system/metrics
    data_stream.namespace: default
    use_output: default
    streams:
      - metricset: cpu
        data_stream.dataset: system.cpu
      - metricset: memory
        data_stream.dataset: system.memory
      - metricset: network
        data_stream.dataset: system.network
      - metricset: filesystem
        data_stream.dataset: system.filesystem

output:

# ----------------------------- Elasticsearch Output ----------------------------

  elasticsearch:
    hosts: ["https://es01.${APP_NET}:${ES_PORT}"]
    protocol: "https"
    username: "${ELASTICSEARCH_USERNAME}"
    password: "${ELASTICSEARCH_PASSWORD}"
    timeout: 20s
    ssl:
      enabled: true
      certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
      verification_mode: "${VERIFICATION_MODE}"
    
#------------------------------ Setup -------------------------------
  
setup:
  ilm.overwrite: true 
  template.settings:
    index.number_of_shards: 2
    index.codec: best_compression
    _source.enabled: false

  elasticsearch:
    hosts: ["https://es01.${APP_NET}:${ES_PORT}"]
    protocol: "https"
    username: "${ELASTICSEARCH_USERNAME}"
    password: "${ELASTICSEARCH_PASSWORD}"
    ssl:
      enabled: true
      certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
      verification_mode: "${VERIFICATION_MODE}"

  kibana:
    host: "http://kibana.${APP_NET}:${KIBANA_PORT}"
    username: "${ELASTICSEARCH_USERNAME}"
    password: "${ELASTICSEARCH_PASSWORD}"
    ssl:
      enabled: false
      # enabled: true
      # certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
      # verification_mode: "${VERIFICATION_MODE}"
