version: '3.9'

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}

services:

  kibana:
    image: nginx:alpine
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      default:
    container_name: "kibana"
    volumes:
      - ./extras/nginx/default-http.conf:/etc/nginx/conf.d/default.conf:ro
      - ./application/html:/var/www/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.work-public.rule=Host(`${KIBANA_HOST}`)"
      - "traefik.http.routers.work-public.entrypoints=https"
      - "traefik.http.routers.work-public.tls=true"
