version: '3.9'

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}

services:

#
# === K - kibana alternate ===
#
  kibana:
    image: nginx:alpine
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      # for traefik:
      default:
    container_name: "${APP_ID}-kibana"
    hostname: "${KIBANA_HOST}"
    volumes:
      - ./extras/nginx/default-http.conf:/etc/nginx/conf.d/default.conf:ro
      - ./application/html:/var/www/html:ro
      - ./logs/nginx:/var/log/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.work-public.rule=Host(`${KIBANA_HOST}`, `work.${KIBANA_HOST}`)"
      - "traefik.http.routers.work-public.entrypoints=https"
      - "traefik.http.routers.work-public.tls=true"
