###################### Filebeat Configuration #######################

http.enabled: true
http.port: 5066
http.host: "${ES_NET}.9"

monitoring:
  enabled: false
  cluster_uuid: "${CLUSTER_UUID}"

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_tags:
      tags: ["${STAGE}"]
      target: "environment"
  - add_tags:
      tags: ["${APP_HOST}-${APP_ID}"]
      target: "app.id"

instrumentation:
  enabled: true
  environment: "${STAGE}"
  hosts: ["${ELASTIC_APM_SERVER_URL}"]
  # api_key: "${ELASTIC_APM_API_KEY}"
  tags: ["${APP_HOST}-${APP_ID}"]

filebeat.inputs:
  - type: filestream
    id: traefik.error
    paths:
      - /usr/share/filebeat/elogs/traefik/${TRAEFIK_LOG}

output:
  logstash:                                        # # 
    enabled: true                                    # 
    hosts: ["logstash.${APP_NET}:${LOGSTASH_PORT}"]  # 
    index: "logs"                                    # 
                                          
  # for /filebeat -e setup --dashboards:                                          #  
  # elasticsearch:                            
  #   hosts: ["https://es01.${APP_NET}:${ES_PORT}"] 
  #   protocol: "https"                       
  #   username: "${ELASTICSEARCH_USERNAME}"
  #   password: "${ELASTICSEARCH_PASSWORD}"
  #   ssl:
  #     enabled: true
  #     certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
  #     verification_mode: "${VERIFICATION_MODE}"
  #   # index: "logs"
  
setup:      
  ilm.overwrite: true
  template.settings:
    index.number_of_shards: 2
    index.codec: best_compression
    _source.enabled: false
  elasticsearch:
    hosts: ["https://es01.${APP_NET}:${ES_PORT}"]
    protocol: "https"
    username: "${ELASTICSEARCH_USERNAME}"
    password: "${ELASTICSEARCH_PASSWORD}"
    ssl:
      enabled: true
      certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]
      verification_mode: "${VERIFICATION_MODE}"

  kibana:
    host: "http://kibana.${APP_NET}:${KIBANA_PORT}"
    username: '${ELASTICSEARCH_USERNAME}'
    password: '${ELASTICSEARCH_PASSWORD}'
    protocol: "http"
    ssl:
      enabled: false
